import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request) {
  try {
    const { name, email, query } = await request.json();

    // Verify environment variables are configured
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS || !process.env.EMAIL_TO) {
      console.error('Nodemailer configuration error: Missing environment variables.');
      return NextResponse.json(
        { success: false, error: 'Internal Server Error: Email service not configured.' },
        { status: 500 }
      );
    }

    // Create a transporter
    const transporter = nodemailer.createTransport({
      service: 'gmail', // easy setup for Gmail apps
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS, // App Password
      },
    });

    const mailOptions = {
      from: `"${name}" <${email}>`,
      to: process.env.EMAIL_TO,
      subject: `📧 Portfolio Message from ${name}`,
      text: `Name: ${name}\nEmail: ${email}\n\nMessage:\n${query}`,
      html: `
        <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f6f9fc;">
          <div style="background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(50, 50, 93, 0.11), 0 1px 3px rgba(0, 0, 0, 0.08);">
            <div style="background: linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%); padding: 25px; text-align: center;">
              <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 600; letter-spacing: 0.5px;">New Contact Message</h1>
              <p style="color: #dbeafe; margin: 5px 0 0; font-size: 14px;">from your Portfolio website</p>
            </div>
            <div style="padding: 30px;">
              <div style="margin-bottom: 25px; border-bottom: 1px solid #e5e7eb; padding-bottom: 15px;">
                <p style="margin: 0 0 5px; font-size: 12px; color: #6b7280; font-weight: 600; text-transform: uppercase;">From</p>
                <p style="margin: 0; font-size: 16px; color: #111827; font-weight: 500;">${name}</p>
              </div>
              
              <div style="margin-bottom: 25px; border-bottom: 1px solid #e5e7eb; padding-bottom: 15px;">
                <p style="margin: 0 0 5px; font-size: 12px; color: #6b7280; font-weight: 600; text-transform: uppercase;">Email Address</p>
                <a href="mailto:${email}" style="margin: 0; font-size: 16px; color: #2563eb; text-decoration: none; font-weight: 500;">${email}</a>
              </div>
              
              <div style="margin-bottom: 0;">
                <p style="margin: 0 0 10px; font-size: 12px; color: #6b7280; font-weight: 600; text-transform: uppercase;">Message</p>
                <div style="background-color: #f9fafb; padding: 15px; border-radius: 6px; border: 1px solid #f3f4f6;">
                  <p style="margin: 0; font-size: 15px; color: #374151; line-height: 1.6; white-space: pre-line;">${query}</p>
                </div>
              </div>
            </div>
            <div style="background-color: #f3f4f6; padding: 15px; text-align: center; border-top: 1px solid #e5e7eb;">
              <p style="margin: 0; font-size: 12px; color: #9ca3af;">This email was automatically generated by your portfolio site.</p>
            </div>
          </div>
        </div>
      `
    };

    await transporter.sendMail(mailOptions);

    return NextResponse.json({ success: true, message: 'Email sent successfully' }, { status: 200 });
  } catch (error) {
    console.error('Nodemailer error:', error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
